#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Primusflex.Mobile.Resource", IsApplication=true)]

namespace Primusflex.Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int generalTextColor = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int menu_help = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int menu_upload = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int selector = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int btnLogin = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int btnOpenCamera = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int editTextPassword = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int editTextUserName = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int imageView2 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int imageView3 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int imageView4 = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout2 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout3 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout4 = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int progressBarCircle = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int textView4 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int textViewErrorMessage = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int view1 = 2131165202;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int offline_home = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int application_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int check_net_text = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int company_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int login_caps = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int offline_message = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int open_camera = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
